### ISSUE TITLE
xiuno bbs 4.0.6 提示插件不存在.....

### ISSUE THREAD

**Issue by m-rouin** [xiulab/xl_editormd#1]

**Comment by skiy** [comment]
> _No description provided._

只发布 `4.0.5` 版本，没有发布 `4.0.6`。另外，插件的安装跟其它的插件是一样的方式，先确认一下插件文件夹的可读性是不是 `777` 的可读可写权限。

**Comment by m-rouin** [comment]
> > _没有提供描述。_
> 
> 仅，发布`4.0.5`版本，没有发布`4.0.6`。另外，插件的安装跟其他的插件是一样的方式，先确认一下插件文件夹的嵌套性是不是`777`的可选可写权限。

好吧,不好意思.....对了大佬方便加个好友吗,我在学习弄vditor md 编辑器 , 有东西不太懂.... QQ: 334472229

**Comment by skiy** [comment]
问题已解决，查看 #2 ，解压后的文件夹名称需要修改为 `xl_editormd`
