### ISSUE TITLE
xiunobbs 4.0.4 安装提示  插件不存在

### ISSUE THREAD

**Issue by haiwan-xm** [xiulab/xl_editormd#2]
xiunobbs 4.0.4 安装提示  插件不存在

**Comment by skiy** [comment]
插件的安装跟其它的插件是一样的方式，先确认一下插件文件夹的可读性是不是 `777` 的可读可写权限。

**Comment by haiwan-xm** [comment]
我反复确认了    插件目录777

**Comment by haiwan-xm** [comment]
![image](https://user-images.githubusercontent.com/45061573/103902713-e27ea800-5135-11eb-8555-955ebd551ff9.png)
![image](https://user-images.githubusercontent.com/45061573/103902734-e90d1f80-5135-11eb-87e6-98569717d56e.png)

**Comment by skiy** [comment]
主仓库在 `Gitee` ，以 `v1.0.1` 版本为例的操作命令为:    
```
# 进入插件目录，再执行 `CURL` 操作命令。
cd plugin
curl -o xl_editormd.zip https://gitee.com/xiulab/xl_editormd/repository/archive/v1.0.1 && unzip xl_editormd.zip && chmod 777 xl_editormd/conf.json
```

进 `xiunobbs` 后台，插件，执行安装即可。

**Comment by skiy** [comment]
看了下，应该是需要修改文件夹名称的，你下载回来解压后还把版本号也带上了，得把它删除掉，最终为 `xl_editormd`
```
XXX/admin/plugin-install-xl_editormd.htm
```

**Comment by haiwan-xm** [comment]
> 看了下，应该是需要修改文件夹名称的，你下载回来解压后还把版本号也带上了，得把它删除掉，最终为 `xl_editormd`
> 
> ```
> XXX/admin/plugin-install-xl_editormd.htm
> ```

多谢老大  搞定了  谢谢    可以加个Q吗
